name: mystore
recipe: drupal9
config:
  webroot: web
services:
  appserver:
    webroot: web
    xdebug: true
    config:
      php: .vscode/php.ini
  node:
    type: node:12
    globals:
      yarn: "latest"
tooling:
  npm:
    service: node
  node:
    service: node