<?php

/**
 * @file
 * Functions to support theming in the mystore theme.
 */

use Drupal\Core\Access\AccessResult;

/**
 * Implements template_preprocess_block.
 */
function mystore_preprocess_block__mystore_nachatprodavat(&$variables)
{
  $stores = \Drupal::entityTypeManager()
    ->getStorage('commerce_store')
    ->loadByProperties([
      'uid' => \Drupal::currentUser()->id(),
    ]);

  if (count($stores) > 0) {
    $variables = [];
  }
}
